server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          default-binder: defaultRabbit
          group: amuA

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳隔离时间（默认30秒）
    lease-expiration-duration-in-seconds: 5 # 超过5秒（默认90秒）
    instance-id: receive-8002.com # 在信息列表时显示主机名称
    prefer-ip-address: true # 访问路径变为ip