server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com/eureka/

ribbon:
  #建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.amu.springCloud.service.PaymentFeignService: debug